sonar.projectKey=fabrijoelc_ms-ordenes
sonar.organization=fabrijoelc
sonar.projectName=ms-ordenes
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
