spring.application.name=hexagonal-sunat

spring.datasource.url=jdbc:postgresql://localhost:5432/hexagonal_sunat
spring.datasource.username=postgres
spring.datasource.password=cero

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

decolecta.api.base-url=https://api.decolecta.com/v1/sunat/
decolecta.api.token=TU_TOKEN_DECOLECTA
