app.message=Mensaje desde mi Config Server DEV
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
management.endpoints.web.exposure.include=refresh,health,info
logging.level.root=INFO
