spring.application.name=apis-externas
decolecta.api.reniec.url=https://api.decolecta.com/v1/reniec
value.token=${DECOLECTA_TOKEN:}
spring.datasource.url=jdbc:postgresql://localhost:5432/apis_externas_db
spring.datasource.username=postgres
spring.datasource.password=cero
spring.jpa.hibernate.ddl-auto=update
