spring.application.name=ms-register-hexagonal

spring.datasource.url=jdbc:postgresql://localhost:5432/ms_register_hexagonal_db
spring.datasource.username=postgres
spring.datasource.password=YOUR_POSTGRES_PASSWORD
spring.jpa.hibernate.ddl-auto=update

spring.data.mongodb.uri=mongodb://localhost:27017/ms_register_hexagonal_mongo_db
spring.data.mongodb.database=ms_register_hexagonal_mongo_db

decolecta.api.reniec.url=https://api.decolecta.com/v1/reniec
token.api=YOUR_DECOLECTA_TOKEN
